#
# THIS CODE AND INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESSED OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS
# FOR A PARTICULAR PURPOSE. THIS CODE AND INFORMATION ARE NOT SUPPORTED BY XEBIALABS.
#
import re

APPLICATION_MATCH_REGEX = re.compile('\^Applications')
ENVIRONMENT_MATCH_REGEX = re.compile('Environments')
DEPLOYMENT_TYPE_LIST = ['initial', 'update', 'rolback']